
#  create_table "producer_images", :force => true do |t|
#    t.integer  "producer_id",                     :null => false
#    t.integer  "sequence",                        :null => false
#    t.string   "alt_text",    :default => "NULL"
#    t.string   "name",        :default => "NULL"
bread.jpg  
field.jpg              
onions.jpg  
spinnach.jpg  
weirdveg.jpg
calf.jpg   
moremixedveg.jpg  
pigs.jpg    
eggs.jpg   
lettuce.jpg            
mushroom.jpg      
vegbox.jpg


