jimmy:
  name: Jimmys Farm
  summary: Breeds rare breed pigs and minor celebraties

mushroom:
  name: Janes Forest shrooms 
  summary: Her squad of hippys find the finest forest fare

baker:
  name: Clopton Farm Bakery
  summary: Bakes amazing breads, cakes and Pies

Veg:
  name: Staunton Vegetables
  summary: Grow unusual vegetables and supply the finest restaurents

Egg:
  name: Harrys Hen House
  summary: Sells all types of eggs from their free range hens

Salad:
  name: Lovely Leaves
  summary: Sell everything you need for an amazing or unusual salad

